---
title: "Untitled"
format: docx
---

```{r}

source("packages.R")

```

```{r}

# load csv file
chem_data <- read.csv("../data/5976423.csv")
```

```{r}
# library(knitr)
# library(officer)
# library(flextable)
# 
# # create a new data frame with only rows with missing data
# missing_rows <- chem_data[apply(chem_data, 1, function(row) any(is.na(row))), ]
# 
# # summarise missing values per column 
# na_counts <- colSums(is.na(missing_rows))
#   
# # calculate percentage of missing values per variable
# na_percent <- round(na_counts/nrow(chem_data)*100, 2)
# 
# # create a table using flextable
# na_var_tbl <- flextable(data.frame(Variable = names(na_counts), Count = na_counts, Percentage = na_percent))
# na_var_tbl <- theme(na_var_tbl, core_bg = "white")
# 
# # summarise missing values by label
# na_summary <- chem_data %>%
#   group_by(label) %>%
#   summarize_all(~ sum(is.na(.)))
# 
# total_obs <- nrow(chem_data)
# 
# row_sums <- data.frame(Label = na_summary$label, 
#                         Count = rowSums(na_summary[,-1]),
#                         Percentage = round(rowSums(na_summary[,-1])/total_obs * 100, 2))
# 
# na_lab_tbl <- flextable(row_sums)
# na_lab_tbl <- theme(na_lab_tbl, core_bg = "white")
# 
# # create a Word document using officer
# doc <- read_docx()
# doc <- body_add_par(doc, "Missing values per variable")
# doc <- body_add_flextable(doc, na_var_tbl)
# doc <- body_add_par(doc, "Missing values by label")
# doc <- body_add_flextable(doc, na_lab_tbl)
# print(doc, target = "output.docx")

```

```{r}
library(flextable)
set_flextable_defaults(
  font.size = 10, border.color = "#3B5998", digits = 2,
  font.family = "Arial", theme_fun = theme_vanilla,
  padding = 6,
  background.color = "#DFE3EE", layout= "autofit", na_str = "<na>")
flextable(iris)
```

```{r}
head(df) |> 
  flextable() |> 
  colformat_double() |> 
  autofit()
```



```{r}


# create a new data frame with only rows with missing data
missing_rows <- chem_data[apply(chem_data, 1, function(row) any(is.na(row))), ]

# summarise missing values per column 
na_counts <- colSums(is.na(missing_rows))
  
# calculate percentage of missing values per variable
na_percent <- round(na_counts/nrow(chem_data)*100, 2)

# create a table using flextable
na_var_tbl <- flextable(data.frame(Variable = names(na_counts), Count = na_counts, Percentage = na_percent))
na_var_tbl <- theme(na_var_tbl, core_bg = "white")

# summarise missing values by label
na_summary <- chem_data %>%
  group_by(label) %>%
  summarize_all(~ sum(is.na(.)))

total_obs <- nrow(chem_data)

row_sums <- data.frame(Label = na_summary$label, 
                        Count = rowSums(na_summary[,-1]),
                        Percentage = round(rowSums(na_summary[,-1])/total_obs * 100, 2))

na_lab_tbl <- flextable(row_sums)
na_lab_tbl <- theme(na_lab_tbl, core_bg = "white")

# create a Word document using ReporteRs
doc <- docx()
doc <- addTitle(doc, "Missing values per variable")
doc <- addFlexTable(doc, as_flextable(na_var_tbl))
doc <- addTitle(doc, "Missing values by label")
doc <- addFlexTable(doc, as_flextable(na_lab_tbl))
writeDoc(doc, "output.docx")

```

